version: '3'

services:
  mailcon:
    image: mailcon
    build:
      context: mailcon
    env_file: .env
    volumes:
      - ${PWD}/mailcon/src:/home/admin/src
      - ${PWD}/images:/home/admin/images
